dc = "euw1-np-dataeng"
environment = "Stag"
region = "eu-west-1"

identifier = "dev-db" 
name = "dev"
instance_class = "db.t2.medium"
storage = "15"
backup_retention_period = "5"
backup_window = "03:51-04:21"
maintenance_window = "sat:22:11-sat:22:41"